-- MySQL Script generated by MySQL Workbench
-- Fri Sep 21 13:51:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema researchdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema researchdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `researchdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `researchdb` ;

-- -----------------------------------------------------
-- Table `researchdb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `icono_g` VARCHAR(45) NOT NULL,
  `icono_p` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`licencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`licencia` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`licencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `licencia` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`revista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`revista` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`revista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(100) NULL,
  `titulo_corto` VARCHAR(45) NULL,
  `issn` VARCHAR(45) NULL,
  `eissn` VARCHAR(45) NULL,
  `doi` VARCHAR(15) NULL,
  `descripcion` MEDIUMTEXT NULL,
  `categoria_id` INT NOT NULL,
  `licencia_id` INT NOT NULL,
  `imagen` VARCHAR(45) NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_revista_categoria1_idx` (`categoria_id` ASC),
  INDEX `fk_revista_licencia1_idx` (`licencia_id` ASC),
  CONSTRAINT `fk_revista_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `researchdb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revista_licencia1`
    FOREIGN KEY (`licencia_id`)
    REFERENCES `researchdb`.`licencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`r_contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`r_contacto` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`r_contacto` (
  `id` INT NOT NULL,
  `institucion` VARCHAR(100) NOT NULL,
  `facultad` VARCHAR(100) NULL,
  `editor` VARCHAR(100) NOT NULL,
  `editor_orcid` VARCHAR(45) NULL,
  `editor_googlescholar` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_contacto_revista1`
    FOREIGN KEY (`id`)
    REFERENCES `researchdb`.`revista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`palabra_clave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`palabra_clave` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`palabra_clave` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `palabra_clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`estilo_citacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`estilo_citacion` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`estilo_citacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estilo_citacion` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`politica_autoarchivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`politica_autoarchivo` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`politica_autoarchivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `politica_autoarchivo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`periodicidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`periodicidad` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`periodicidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `periodicidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`tipo_revision_pares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`tipo_revision_pares` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`tipo_revision_pares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_revision_pares` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`r_adicional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`r_adicional` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`r_adicional` (
  `id` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `twitter` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `instagram` VARCHAR(45) NULL,
  `url` VARCHAR(100) NOT NULL,
  `guia_autores` VARCHAR(100) NOT NULL,
  `equipo_editorial` VARCHAR(100) NOT NULL,
  `codigo_etica` VARCHAR(100) NOT NULL,
  `oai` VARCHAR(100) NOT NULL,
  `preprint` TINYINT NOT NULL,
  `estilo_citacion_id` INT NOT NULL,
  `politica_autoarchivo_id` INT NOT NULL,
  `googlescholar` VARCHAR(100) NULL,
  `videopresentacion` VARCHAR(100) NULL,
  `periodicidad_id` INT NOT NULL,
  `periodicidad_otro` VARCHAR(45) NULL,
  `tipo_revision_pares_id` INT NOT NULL,
  `disciplina_id` INT NOT NULL,
  `disciplina_id1` INT NULL,
  `disciplina_id2` INT NULL,
  `disciplina_id3` INT NULL,
  `apc` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_r_adicional_estilo_citacion1_idx` (`estilo_citacion_id` ASC),
  INDEX `fk_r_adicional_politica_autoarchivo1_idx` (`politica_autoarchivo_id` ASC),
  INDEX `fk_r_adicional_periodicidad1_idx` (`periodicidad_id` ASC),
  INDEX `fk_r_adicional_tipo_revision_pares1_idx` (`tipo_revision_pares_id` ASC),
  INDEX `fk_r_adicional_disciplina1_idx` (`disciplina_id` ASC),
  INDEX `fk_r_adicional_disciplina2_idx` (`disciplina_id1` ASC),
  INDEX `fk_r_adicional_disciplina3_idx` (`disciplina_id2` ASC),
  INDEX `fk_r_adicional_disciplina4_idx` (`disciplina_id3` ASC),
  CONSTRAINT `fk_social_revista1`
    FOREIGN KEY (`id`)
    REFERENCES `researchdb`.`revista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_adicional_estilo_citacion1`
    FOREIGN KEY (`estilo_citacion_id`)
    REFERENCES `researchdb`.`estilo_citacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_adicional_politica_autoarchivo1`
    FOREIGN KEY (`politica_autoarchivo_id`)
    REFERENCES `researchdb`.`politica_autoarchivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_adicional_periodicidad1`
    FOREIGN KEY (`periodicidad_id`)
    REFERENCES `researchdb`.`periodicidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_adicional_tipo_revision_pares1`
    FOREIGN KEY (`tipo_revision_pares_id`)
    REFERENCES `researchdb`.`tipo_revision_pares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_adicional_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `researchdb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_adicional_disciplina2`
    FOREIGN KEY (`disciplina_id1`)
    REFERENCES `researchdb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_adicional_disciplina3`
    FOREIGN KEY (`disciplina_id2`)
    REFERENCES `researchdb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_adicional_disciplina4`
    FOREIGN KEY (`disciplina_id3`)
    REFERENCES `researchdb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`pais` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`estado` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_pais1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `researchdb`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudad_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_ciudad_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `researchdb`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`r_ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`r_ubicacion` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`r_ubicacion` (
  `id` INT NOT NULL,
  `zipcode` VARCHAR(15) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `ciudad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_r_ubicacion_ciudad1_idx` (`ciudad_id` ASC),
  CONSTRAINT `fk_ubicacion_revista1`
    FOREIGN KEY (`id`)
    REFERENCES `researchdb`.`revista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_ubicacion_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `researchdb`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`idioma` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`idioma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`indexaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`indexaciones` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`indexaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `indexaciones` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`r_indexaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`r_indexaciones` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`r_indexaciones` (
  `revista_id` INT NOT NULL,
  `indexaciones_id` INT NOT NULL,
  `parametro` VARCHAR(100) NOT NULL,
  INDEX `fk_r_indexaciones_indexaciones1_idx` (`indexaciones_id` ASC),
  INDEX `fk_r_indexaciones_revista1_idx` (`revista_id` ASC),
  CONSTRAINT `fk_r_indexaciones_indexaciones1`
    FOREIGN KEY (`indexaciones_id`)
    REFERENCES `researchdb`.`indexaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_indexaciones_revista1`
    FOREIGN KEY (`revista_id`)
    REFERENCES `researchdb`.`revista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`r_idiomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`r_idiomas` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`r_idiomas` (
  `idioma_id` INT NOT NULL,
  `revista_id` INT NOT NULL,
  INDEX `fk_r_idiomas_idioma1_idx` (`idioma_id` ASC),
  INDEX `fk_r_idiomas_r_adicional1_idx` (`revista_id` ASC),
  CONSTRAINT `fk_r_idiomas_idioma1`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `researchdb`.`idioma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_idiomas_r_adicional1`
    FOREIGN KEY (`revista_id`)
    REFERENCES `researchdb`.`r_adicional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `researchdb`.`palabras_clave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`palabras_clave` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`palabras_clave` (
  `revista_id` INT NOT NULL,
  `palabra_clave_id` INT NOT NULL,
  INDEX `fk_palabras_clave_revista1_idx` (`revista_id` ASC),
  INDEX `fk_palabras_clave_palabra_clave1_idx` (`palabra_clave_id` ASC),
  CONSTRAINT `fk_palabras_clave_revista1`
    FOREIGN KEY (`revista_id`)
    REFERENCES `researchdb`.`revista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_palabras_clave_palabra_clave1`
    FOREIGN KEY (`palabra_clave_id`)
    REFERENCES `researchdb`.`palabra_clave` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
