-- MySQL Script generated by MySQL Workbench
-- Thu Sep 27 11:52:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `revista` CHANGE `descripcion` `descripcion` MEDIUMTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
--------------------------

ALTER TABLE `radicional` ADD `tiempo_promedio_publicacion` INT NULL AFTER `apc`;
-----------------

ALTER TABLE `editorpropietario` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT;


------------------

CREATE TABLE verificationCode( id integer AUTO_INCREMENT PRIMARY KEY, code text not null, type varchar(255) not null )

CREATE TABLE IF NOT EXISTS `editorpropietario` ( 
  `id` INT(11) NOT NULL AUTO_INCREMENT, 
  `editor_id` INT(11) NOT NULL, 
  `revista_id` INT(11) NOT NULL, 
  PRIMARY KEY (`id`), 
  CONSTRAINT `fk_editorpropietario` FOREIGN KEY (`editor_id`) REFERENCES `editor` (`id`), 
  CONSTRAINT `fk_revistapropietario` FOREIGN KEY (`revista_id`) REFERENCES `revista` (`id`)
) CHARACTER SET = latin1

CREATE TABLE IF NOT EXISTS `suscripcioneditorrevista` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `editor_id` INT(11) NOT NULL,
  `revista_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_editorrevistasuscripcion`
    FOREIGN KEY (`editor_id`)
    REFERENCES `editor` (`id`),
  CONSTRAINT `fk_revistaeditorsuscripcion`
    FOREIGN KEY (`revista_id`)
    REFERENCES `revista` (`id`))
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `suscripcioneditorcategoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `editor_id` INT(11) NOT NULL,
  `categoria_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_editorcategoriasuscripcion`
    FOREIGN KEY (`editor_id`)
    REFERENCES `editor` (`id`),
  CONSTRAINT `fk_categoriaeditorsuscripcion`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria` (`id`))
DEFAULT CHARACTER SET = latin1;

ALTER TABLE revista ADD esta_activa BOOLEAN NOT NULL DEFAULT TRUE

CREATE TABLE IF NOT EXISTS `editor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT,
  `profesion` VARCHAR(255) NOT NULL,
  `imagen` TEXT NULL,
  `realm` TEXT NULL,
  `username` TEXT NULL,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `emailVerified` BOOLEAN NOT NULL,
  `verificationToken` TEXT NULL,
  `universidad` TEXT NULL,
  `nivelAcademico` ENUM('Pregrado/Universitario','Especialización','Especialidad medica','MBA','Maestría/Magister','Doctorado','Pos-doctorado/Estancia pos-doctoral','Otro') NOT NULL,
  `orcid` TEXT NULL,
  `googlescholar` TEXT NULL,
  PRIMARY KEY (`id`)
)

-- -----------------------------------------------------
-- Schema researchdb
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `convocatoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `titulo` TEXT NOT NULL,
  `imagen` TEXT NULL,
  `video` TEXT NULL,
  `link` TEXT NULL,
  `documento_pdf` TEXT NULL,
  `revistaId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_convocatoria_revista`
    FOREIGN KEY (`revistaId`)
    REFERENCES `revista` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Schema researchdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `researchdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `researchdb` ;

-- -----------------------------------------------------
-- Table `researchdb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `icono_g` VARCHAR(45) NOT NULL,
  `icono_p` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`pais` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`pais` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`estado` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`estado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `pais_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_pais1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `researchdb`.`pais` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`ciudad` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudad_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_ciudad_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `researchdb`.`estado` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`disciplina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`estilocitacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`estilocitacion` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`estilocitacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estilo_citacion` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`idioma` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`idioma` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idioma` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`indexaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`indexaciones` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`indexaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `indexaciones` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`licencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`licencia` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`licencia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `licencia` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`palabraclave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`palabraclave` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`palabraclave` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `palabra_clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`revista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`revista` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`revista` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(100) NULL DEFAULT NULL,
  `titulo_corto` VARCHAR(45) NULL DEFAULT NULL,
  `issn` VARCHAR(45) NULL DEFAULT NULL,
  `eissn` VARCHAR(45) NULL DEFAULT NULL,
  `doi` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` MEDIUMTEXT NULL DEFAULT NULL,
  `categoria_id` INT(11) NOT NULL,
  `licencia_id` INT(11) NOT NULL,
  `imagen` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `esta_activa` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`id`),
  INDEX `fk_revista_categoria1_idx` (`categoria_id` ASC),
  INDEX `fk_revista_licencia1_idx` (`licencia_id` ASC),
  CONSTRAINT `fk_revista_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `researchdb`.`categoria` (`id`),
  CONSTRAINT `fk_revista_licencia1`
    FOREIGN KEY (`licencia_id`)
    REFERENCES `researchdb`.`licencia` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`palabrasclave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`palabrasclave` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`palabrasclave` (
  `revista_id` INT(11) NOT NULL,
  `palabra_clave_id` INT(11) NOT NULL,
  INDEX `fk_palabras_clave_revista1_idx` (`revista_id` ASC),
  INDEX `fk_palabras_clave_palabra_clave1_idx` (`palabra_clave_id` ASC),
  CONSTRAINT `fk_palabras_clave_palabra_clave1`
    FOREIGN KEY (`palabra_clave_id`)
    REFERENCES `researchdb`.`palabraclave` (`id`),
  CONSTRAINT `fk_palabras_clave_revista1`
    FOREIGN KEY (`revista_id`)
    REFERENCES `researchdb`.`revista` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`periodicidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`periodicidad` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`periodicidad` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `periodicidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`politicaautoarchivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`politicaautoarchivo` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`politicaautoarchivo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `politica_autoarchivo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`tiporevisionpares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`tiporevisionpares` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`tiporevisionpares` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_revision_pares` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`radicional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`radicional` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`radicional` (
  `id` INT(11) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `twitter` VARCHAR(100) NULL DEFAULT NULL,
  `facebook` VARCHAR(100) NULL DEFAULT NULL,
  `instagram` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(100) NOT NULL,
  `guia_autores` VARCHAR(145) NOT NULL,
  `equipo_editorial` VARCHAR(145) NOT NULL,
  `codigo_etica` VARCHAR(100) NOT NULL,
  `oai` VARCHAR(100) NOT NULL,
  `preprint` TINYINT(4) NOT NULL,
  `estilo_citacion_id` INT(11) NOT NULL,
  `politica_autoarchivo_id` INT(11) NOT NULL,
  `googlescholar` VARCHAR(100) NULL DEFAULT NULL,
  `videopresentacion` VARCHAR(100) NULL DEFAULT NULL,
  `periodicidad_id` INT(11) NOT NULL,
  `periodicidad_otro` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_revision_pares_id` INT(11) NOT NULL,
  `disciplina_id` INT(11) NOT NULL,
  `disciplina_id1` INT(11) NULL DEFAULT NULL,
  `disciplina_id2` INT(11) NULL DEFAULT NULL,
  `disciplina_id3` INT(11) NULL DEFAULT NULL,
  `apc` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_r_adicional_estilo_citacion1_idx` (`estilo_citacion_id` ASC),
  INDEX `fk_r_adicional_politica_autoarchivo1_idx` (`politica_autoarchivo_id` ASC),
  INDEX `fk_r_adicional_periodicidad1_idx` (`periodicidad_id` ASC),
  INDEX `fk_r_adicional_tipo_revision_pares1_idx` (`tipo_revision_pares_id` ASC),
  INDEX `fk_r_adicional_disciplina1_idx` (`disciplina_id` ASC),
  INDEX `fk_r_adicional_disciplina2_idx` (`disciplina_id1` ASC),
  INDEX `fk_r_adicional_disciplina3_idx` (`disciplina_id2` ASC),
  INDEX `fk_r_adicional_disciplina4_idx` (`disciplina_id3` ASC),
  CONSTRAINT `fk_r_adicional_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `researchdb`.`disciplina` (`id`),
  CONSTRAINT `fk_r_adicional_disciplina2`
    FOREIGN KEY (`disciplina_id1`)
    REFERENCES `researchdb`.`disciplina` (`id`),
  CONSTRAINT `fk_r_adicional_disciplina3`
    FOREIGN KEY (`disciplina_id2`)
    REFERENCES `researchdb`.`disciplina` (`id`),
  CONSTRAINT `fk_r_adicional_disciplina4`
    FOREIGN KEY (`disciplina_id3`)
    REFERENCES `researchdb`.`disciplina` (`id`),
  CONSTRAINT `fk_r_adicional_estilo_citacion1`
    FOREIGN KEY (`estilo_citacion_id`)
    REFERENCES `researchdb`.`estilocitacion` (`id`),
  CONSTRAINT `fk_r_adicional_periodicidad1`
    FOREIGN KEY (`periodicidad_id`)
    REFERENCES `researchdb`.`periodicidad` (`id`),
  CONSTRAINT `fk_r_adicional_politica_autoarchivo1`
    FOREIGN KEY (`politica_autoarchivo_id`)
    REFERENCES `researchdb`.`politicaautoarchivo` (`id`),
  CONSTRAINT `fk_r_adicional_tipo_revision_pares1`
    FOREIGN KEY (`tipo_revision_pares_id`)
    REFERENCES `researchdb`.`tiporevisionpares` (`id`),
  CONSTRAINT `fk_social_revista1`
    FOREIGN KEY (`id`)
    REFERENCES `researchdb`.`revista` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`rcontacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`rcontacto` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`rcontacto` (
  `id` INT(11) NOT NULL,
  `institucion` VARCHAR(100) NOT NULL,
  `facultad` VARCHAR(100) NULL DEFAULT NULL,
  `editor` VARCHAR(100) NOT NULL,
  `editor_orcid` VARCHAR(45) NULL DEFAULT NULL,
  `editor_googlescholar` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_contacto_revista1`
    FOREIGN KEY (`id`)
    REFERENCES `researchdb`.`revista` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`ridiomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`ridiomas` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`ridiomas` (
  `idioma_id` INT(11) NOT NULL,
  `revista_id` INT(11) NOT NULL,
  INDEX `fk_r_idiomas_idioma1_idx` (`idioma_id` ASC),
  INDEX `fk_r_idiomas_r_adicional1_idx` (`revista_id` ASC),
  CONSTRAINT `fk_r_idiomas_idioma1`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `researchdb`.`idioma` (`id`),
  CONSTRAINT `fk_r_idiomas_r_adicional1`
    FOREIGN KEY (`revista_id`)
    REFERENCES `researchdb`.`radicional` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`rindexaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`rindexaciones` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`rindexaciones` (
  `revista_id` INT(11) NOT NULL,
  `indexaciones_id` INT(11) NOT NULL,
  `parametro` VARCHAR(100) NOT NULL,
  INDEX `fk_r_indexaciones_indexaciones1_idx` (`indexaciones_id` ASC),
  INDEX `fk_r_indexaciones_revista1_idx` (`revista_id` ASC),
  CONSTRAINT `fk_r_indexaciones_indexaciones1`
    FOREIGN KEY (`indexaciones_id`)
    REFERENCES `researchdb`.`indexaciones` (`id`),
  CONSTRAINT `fk_r_indexaciones_revista1`
    FOREIGN KEY (`revista_id`)
    REFERENCES `researchdb`.`revista` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `researchdb`.`rubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `researchdb`.`rubicacion` ;

CREATE TABLE IF NOT EXISTS `researchdb`.`rubicacion` (
  `id` INT(11) NOT NULL,
  `zipcode` VARCHAR(15) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_r_ubicacion_ciudad1_idx` (`ciudad_id` ASC),
  CONSTRAINT `fk_r_ubicacion_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `researchdb`.`ciudad` (`id`),
  CONSTRAINT `fk_ubicacion_revista1`
    FOREIGN KEY (`id`)
    REFERENCES `researchdb`.`revista` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
